FROM ruby:2.7.5

RUN apt-get update &&  apt-get install -y \
  build-essential \
  default-libmysqlclient-dev \
  imagemagick \
  git-core \
  && apt-get autoremove \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV RAILS_ROOT /app
WORKDIR $RAILS_ROOT

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v 2.3.3
RUN bundle install --jobs 20 --retry 5

COPY . ./

CMD ["sidekiq", "-C", "config/sidekiq.yml"]
